app/routes/prestamo.py
from flask import Blueprint, render_template, request, redirect, flash, url_for, session
from models.controladordatabase import db, Prestamo, Libros, Usuario, Autor, Genero, Editorial
from datetime import date, timedelta, datetime
from routes.login import login_required, admin_required

prestamos = Blueprint('prestamos', __name__)

@prestamos.route('/todos-los-prestamos')
@admin_required
def ver_todos_prestamos():
    page = request.args.get('page', 1, type=int)
    per_page = 20
    nombre_usuario = request.args.get('usuario', '', type=str)
    titulo_libro = request.args.get('titulo_libro', '', type=str)

    query = db.session.query(Prestamo, Libros, Usuario).join(Libros, Prestamo.id_libro == Libros.id).join(Usuario, Prestamo.id_usuario == Usuario.id)

    if nombre_usuario:
        query = query.filter(Usuario.nombre.ilike(f"%{nombre_usuario}%"))
    if titulo_libro:
        query = query.filter(Libros.titulo.ilike(f"%{titulo_libro}%"))

    pagination = query.paginate(page=page, per_page=per_page)

    return render_template('prestamos/todos.html', prestamos=pagination.items, pagination=pagination)

@prestamos.route('/editar-prestamo/<int:id>', methods=['GET', 'POST'])
@admin_required
def editar_prestamo(id):
    prestamo = Prestamo.query.get_or_404(id)
    
    if request.method == 'POST':
        fecha_devolucion = request.form.get('fecha_devolucion')
        if fecha_devolucion:
            try:
                prestamo.fecha_devolucion = datetime.strptime(fecha_devolucion, '%Y-%m-%d').date()
                db.session.commit()
                flash('Préstamo actualizado con éxito.', 'success')
            except ValueError as ve:
                flash(f'Formato de fecha inválido: {str(ve)}', 'error')
            except Exception as e:
                db.session.rollback()
                flash(f'Error al actualizar el préstamo: {str(e)}', 'error')
        
        return redirect(url_for('prestamos.ver_todos_prestamos'))
    
    return render_template('prestamos/editar.html', prestamo=prestamo)

@prestamos.route('/eliminar-prestamo/<int:id>', methods=['POST', 'GET'])
@login_required
def eliminar_prestamo(id):
    prestamo = Prestamo.query.get_or_404(id)
    libro = Libros.query.get_or_404(prestamo.id_libro)  
    
    try:
        libro.stock += 1
        db.session.delete(prestamo)
        db.session.commit()
        flash('Préstamo eliminado y stock del libro actualizado con éxito.', 'success')
    except Exception as e:
        db.session.rollback()
        flash(f'Error al eliminar el préstamo: {str(e)}', 'error')
    
    return redirect(request.referrer)

@prestamos.route('/mis-prestamos')
@login_required
def listar_prestamos():
    usuario_id = Usuario.query.filter_by(nombre=session['nombre']).first().id
    
    prestamos = db.session.query(Prestamo, Libros).join(Libros, Prestamo.id_libro == Libros.id).filter(Prestamo.id_usuario == usuario_id).all()
    
    total_precios = round(sum([prestamo.precio_final for prestamo, _ in prestamos]))

    return render_template('prestamos/listar.html', prestamos=prestamos, total_precios=total_precios)

@prestamos.route('/solicitar-prestamo/<int:libro_id>', methods=['POST'])
@login_required
def solicitar_prestamo(libro_id):
    libro = Libros.query.get(libro_id)

    if not libro:
        flash('Libro no encontrado.', 'error')
        return redirect(url_for('libros.detalle', libro_id=libro_id))

    if libro.stock <= 0:
        flash('No hay stock disponible para este libro.', 'error')
        return redirect(url_for('libros.detalle', libro_id=libro.id))

    usuario = Usuario.query.filter_by(nombre=session['nombre']).first()

    if not usuario:
        flash('Usuario no encontrado.', 'error')
        return redirect(url_for('user.logout'))

    usuario_id = usuario.id

    duracion_dias = int(request.form['duracion'])
    fecha_prestamo = date.today()
    fecha_devolucion = fecha_prestamo + timedelta(days=duracion_dias)

    if duracion_dias == 30:
        precio_final = libro.precio_alquiler * 2
    elif duracion_dias == 40:
        precio_final = libro.precio
    else:
        precio_final = libro.precio_alquiler

    nuevo_prestamo = Prestamo(
        id_libro=libro.id,
        id_usuario=usuario_id,
        precio_final=precio_final,
        fecha_devolucion=fecha_devolucion  
    )

    libro.stock -= 1

    try:
        db.session.add(nuevo_prestamo)
        db.session.commit()
        flash(f'Préstamo del libro "{libro.titulo}" realizado con éxito. Precio final: ${precio_final}', 'success')
    except Exception as e:
        db.session.rollback()
        flash(f'Error al realizar el préstamo: {str(e)}', 'error')

    return redirect(url_for('libros.detalle', libro_id=libro_id))

app/templates/prestamos/detalle_libro.html
{% extends 'layout.html' %}

{% block content %}
<body>
    <h1>{{ libro.titulo }}</h1>
    <img src="{{ url_for('static', filename='images/' + libro.img) }}" alt="{{ libro.titulo }}" width="150">
    <p><strong>Autor:</strong> {{ libro.autor }}</p>
    <p><strong>Descripción:</strong> {{ libro.descripcion }}</p>
    <p><strong>Fecha de Emisión:</strong> {{ libro.fecha_emision }}</p>
    <p><strong>Precio:</strong> ${{ libro.precio }}</p>
    <p><strong>Stock Disponible:</strong> {{ libro.stock }}</p>

    {% if libro.stock > 0 %}
    <form action="{{ url_for('prestamos.solicitar_prestamo', libro_id=libro.id) }}" method="POST">
        <button type="submit">Solicitar Préstamo</button>
    </form>
    {% else %}
    <p>No hay stock disponible para este libro.</p>
    {% endif %}
    
    <a href="{{ url_for('libros.listar') }}">Volver a la lista de libros</a>
    {% endblock %}
    
</body>
</html>

app/templates/prestamos/editar.html
{% extends 'layout.html' %}

{% block content %}
<body>
    <h1>Editar Préstamo</h1>

    <form method="POST" action="{{ url_for('prestamos.editar_prestamo', id=prestamo.id) }}">
        <label for="fecha_devolucion">Fecha de Devolución:</label>
        <input type="date" id="fecha_devolucion" name="fecha_devolucion" value="{{ prestamo.fecha_devolucion }}">

        <button type="submit">Guardar cambios</button>
    </form>

    <a href="{{ url_for('prestamos.ver_todos_prestamos') }}">Volver a la lista</a>
    {% endblock %}
</body>
</html>

app/templates/prestamos/listar.html
{% extends 'layout.html' %}

{% block content %}<body>
    <main id="main" class="flexbox-col">

    <h1>Mi Carrito</h1>
    
    <table>
        <thead>
            <tr>
                <th>Libro</th>
                <th>Fecha de Préstamo</th>
                <th>Fecha de Devolución</th>
                <th>Precio</th>
            </tr>
        </thead>
        <tbody>
            {% for prestamo, libro in prestamos %}
            <tr>
                <td data-label="Libro">{{ prestamo.libro.titulo }}</td>
                <td data-label="Fecha Prestamo">{{ prestamo.fecha_prestamo }}</td>
                <td data-label="Fecha Devolucion">{{ prestamo.fecha_devolucion if prestamo.fecha_devolucion else 'Pendiente' }}</td>
                <td data-label="Precio">{{ prestamo.precio_final }}</td>
                <td><form action="{{ url_for('prestamos.eliminar_prestamo', id=prestamo.id) }}" method="post" style="display:inline;">
                    <button style="width: 100px; height: 40px; background-color: rgb(182, 114, 114);" type="submit" onclick="return confirm('¿Estás seguro de que deseas eliminar este préstamo?');">Eliminar</button>
                </form></td>
            </tr>
            {% endfor %}
            
        </tbody>
    </table>
    <p><strong style="color: #e63946;">Total de precios de los préstamos: ${{ total_precios }}</strong></p>
    </main>
    {% endblock %}
</body>
</html>

app/templates/prestamos/todos.html
{% extends 'layout.html' %}

{% block content %}
<body>
    
    <h1>Listado de todos los préstamos</h1>

    <form method="GET" action="{{ url_for('prestamos.ver_todos_prestamos') }}">
        <input type="text" name="usuario" placeholder="Nombre de usuario" value="{{ request.args.get('usuario', '') }}">
        <input type="text" name="titulo_libro" placeholder="Título del libro" value="{{ request.args.get('titulo_libro', '') }}">
        <button type="submit">Buscar</button>
    </form>

    <table border="1">
        <thead>
            <tr>
                <th>Usuario</th>
                <th>Libro</th>
                <th>Fecha Préstamo</th>
                <th>Fecha Devolución</th>
                <th>Precio Final</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for prestamo, libro, usuario in prestamos %}
                <tr>
                    <td data-label="Usuario">{{ usuario.nombre }}</td>
                    <td data-label="Libro">{{ libro.titulo }}</td>
                    <td data-label="Fecha Préstamo">{{ prestamo.fecha_prestamo }}</td>
                    <td data-label="Fecha Devolución">{{ prestamo.fecha_devolucion }}</td>
                    <td data-label="Precio Final">${{ prestamo.precio_final }}</td>
                    <td>
                        <a class="linkedit" style="color: aliceblue; background-color: #28a745; border-radius: 30%; padding: 5px;" href="{{ url_for('prestamos.editar_prestamo', id=prestamo.id) }}">Editar</a>
                        <form method="POST" action="{{ url_for('prestamos.eliminar_prestamo', id=prestamo.id) }}" style="display:inline;">
                            <button type="submit" style="background-color: rgb(192, 76, 76);">Eliminar</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <div>
        {% if pagination.has_prev %}
            <a href="{{ url_for('prestamos.ver_todos_prestamos', page=pagination.prev_num) }}">Anterior</a>
        {% endif %}
        {% if pagination.has_next %}
            <a href="{{ url_for('prestamos.ver_todos_prestamos', page=pagination.next_num) }}">Siguiente</a>
        {% endif %}
    </div>
    </table>


    <ul class="pagination">
        {% if pagination.has_prev %}
        <li><a href="{{ url_for('prestamos.ver_todos_prestamos', page=pagination.prev_num) }}">Anterior</a></li>
        {% endif %}
        
        {% for page_num in pagination.iter_pages(left_edge=1, right_edge=1, left_current=2, right_current=2) %}
            {% if page_num %}
                {% if page_num == pagination.page %}
                    <li class="active"><strong>{{ page_num }}</strong></li>
                {% else %}
                    <li><a href="{{ url_for('prestamos.ver_todos_prestamos', page=page_num) }}">{{ page_num }}</a></li>
                {% endif %}
            {% else %}
                <li class="li">…</li>
            {% endif %}
        {% endfor %}

        {% if pagination.has_next %}
        <li><a href="{{ url_for('prestamos.ver_todos_prestamos', page=pagination.next_num) }}">Siguiente</a></li>
        {% endif %}
    </ul>


    </main>

{% endblock %}
</body>
</html>