app/routes/login.py
from flask import Blueprint,render_template,request,redirect,flash,jsonify,url_for,session
from models.controladordatabase import db,Usuario
from functools import wraps


def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if "nombre" not in session:
            flash("Por favor, inicia sesión para acceder a esta página.")
            return redirect(url_for('user.index_login'))
        return f(*args, **kwargs)
    return decorated_function

def admin_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if "nombre" not in session: 
            flash("Acceso denegado: Debes iniciar sesión.")
            return redirect(url_for('user.index_login'))  
        
        if session.get('rol') != 'admin':  
            flash("Acceso denegado: Se requiere rol de administrador.")
            return redirect(url_for('libros.bienvenida'))  
            
        return f(*args, **kwargs)
    return decorated_function


user = Blueprint('user',__name__)

@user.route("/index_login")
def index_login():
    if "nombre" in session:
        return redirect(url_for('libros.bienvenida'))
    return render_template("usuarios/login.html")



@user.route("/login", methods=["POST"])
def login():
    nombre = request.form['nombre']
    contrasena = request.form['contrasena']
    
    user = Usuario.query.filter_by(nombre=nombre).first()
    
    if user and user.check_password(contrasena):
        session['nombre'] = nombre
        session['rol'] = user.rol
        session['usuario_id'] = user.id  
    
        return redirect(url_for('libros.bienvenida'))
    else:
        return render_template("usuarios/login.html", error="Credenciales incorrectas")

    
@user.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        nombre = request.form['nombre']
        contrasena = request.form['contrasena']
        correo = request.form['correo']
        tel_cel = request.form['tel_cel']

        user = Usuario.query.filter_by(nombre=nombre).first()
        if user:
            return render_template("usuarios/register.html", error="Usuario ya registrado")
        else:
            nuevo_usuario = Usuario(nombre=nombre, correo=correo, tel_cel=tel_cel)
            nuevo_usuario.set_password(contrasena)
            db.session.add(nuevo_usuario)
            db.session.commit()
            
            flash("Registro exitoso. Por favor, inicia sesión.")
            return redirect(url_for('user.index_login'))
    
    return render_template("usuarios/register.html")


@user.route("/logout")
def logout():
    session.pop('nombre', None)
    session.pop('rol', None)
    session.pop('usuario_id', None)
    return redirect(url_for('user.index_login'))

app/routes/prestamo.py
from flask import Blueprint, render_template, request, redirect, flash, url_for, session
from models.controladordatabase import db, Prestamo, Libros, Usuario, Autor, Genero, Editorial
from datetime import date, timedelta, datetime
from routes.login import login_required, admin_required

prestamos = Blueprint('prestamos', __name__)

@prestamos.route('/todos-los-prestamos')
@admin_required
def ver_todos_prestamos():
    page = request.args.get('page', 1, type=int)
    per_page = 20
    nombre_usuario = request.args.get('usuario', '', type=str)
    titulo_libro = request.args.get('titulo_libro', '', type=str)

    query = db.session.query(Prestamo, Libros, Usuario).join(Libros, Prestamo.id_libro == Libros.id).join(Usuario, Prestamo.id_usuario == Usuario.id)

    if nombre_usuario:
        query = query.filter(Usuario.nombre.ilike(f"%{nombre_usuario}%"))
    if titulo_libro:
        query = query.filter(Libros.titulo.ilike(f"%{titulo_libro}%"))

    pagination = query.paginate(page=page, per_page=per_page)

    return render_template('prestamos/todos.html', prestamos=pagination.items, pagination=pagination)

@prestamos.route('/editar-prestamo/<int:id>', methods=['GET', 'POST'])
@admin_required
def editar_prestamo(id):
    prestamo = Prestamo.query.get_or_404(id)
    
    if request.method == 'POST':
        fecha_devolucion = request.form.get('fecha_devolucion')
        if fecha_devolucion:
            try:
                prestamo.fecha_devolucion = datetime.strptime(fecha_devolucion, '%Y-%m-%d').date()
                db.session.commit()
                flash('Préstamo actualizado con éxito.', 'success')
            except ValueError as ve:
                flash(f'Formato de fecha inválido: {str(ve)}', 'error')
            except Exception as e:
                db.session.rollback()
                flash(f'Error al actualizar el préstamo: {str(e)}', 'error')
        
        return redirect(url_for('prestamos.ver_todos_prestamos'))
    
    return render_template('prestamos/editar.html', prestamo=prestamo)

@prestamos.route('/eliminar-prestamo/<int:id>', methods=['POST', 'GET'])
@login_required
def eliminar_prestamo(id):
    prestamo = Prestamo.query.get_or_404(id)
    libro = Libros.query.get_or_404(prestamo.id_libro)  
    
    try:
        libro.stock += 1
        db.session.delete(prestamo)
        db.session.commit()
        flash('Préstamo eliminado y stock del libro actualizado con éxito.', 'success')
    except Exception as e:
        db.session.rollback()
        flash(f'Error al eliminar el préstamo: {str(e)}', 'error')
    
    return redirect(request.referrer)

@prestamos.route('/mis-prestamos')
@login_required
def listar_prestamos():
    usuario_id = Usuario.query.filter_by(nombre=session['nombre']).first().id
    
    prestamos = db.session.query(Prestamo, Libros).join(Libros, Prestamo.id_libro == Libros.id).filter(Prestamo.id_usuario == usuario_id).all()
    
    total_precios = round(sum([prestamo.precio_final for prestamo, _ in prestamos]))

    return render_template('prestamos/listar.html', prestamos=prestamos, total_precios=total_precios)

@prestamos.route('/solicitar-prestamo/<int:libro_id>', methods=['POST'])
@login_required
def solicitar_prestamo(libro_id):
    libro = Libros.query.get(libro_id)

    if not libro:
        flash('Libro no encontrado.', 'error')
        return redirect(url_for('libros.detalle', libro_id=libro_id))

    if libro.stock <= 0:
        flash('No hay stock disponible para este libro.', 'error')
        return redirect(url_for('libros.detalle', libro_id=libro.id))

    usuario = Usuario.query.filter_by(nombre=session['nombre']).first()

    if not usuario:
        flash('Usuario no encontrado.', 'error')
        return redirect(url_for('user.logout'))

    usuario_id = usuario.id

    duracion_dias = int(request.form['duracion'])
    fecha_prestamo = date.today()
    fecha_devolucion = fecha_prestamo + timedelta(days=duracion_dias)

    if duracion_dias == 30:
        precio_final = libro.precio_alquiler * 2
    elif duracion_dias == 40:
        precio_final = libro.precio
    else:
        precio_final = libro.precio_alquiler

    nuevo_prestamo = Prestamo(
        id_libro=libro.id,
        id_usuario=usuario_id,
        precio_final=precio_final,
        fecha_devolucion=fecha_devolucion  
    )

    libro.stock -= 1

    try:
        db.session.add(nuevo_prestamo)
        db.session.commit()
        flash(f'Préstamo del libro "{libro.titulo}" realizado con éxito. Precio final: ${precio_final}', 'success')
    except Exception as e:
        db.session.rollback()
        flash(f'Error al realizar el préstamo: {str(e)}', 'error')

    return redirect(url_for('libros.detalle', libro_id=libro_id))

app/templates/agregarlibro.html
{% extends 'layout.html' %}

{% block content %}
<h1>añadir libro</h1>


    <form action="/agregarlibro" method="post">
        <input type="text" name="nombre_libro" placeholder="nombre del libro"><br><br>
        <input type="text" name="autor" placeholder="nombre del autor"><br><br>
        <input type="date" name="fecha_creacion" placeholder="fecha de salida"><br><br>
        <input type="number" name="stock" placeholder="stock"><br><br>
        <input type="number" name="precio" placeholder="precio"><br><br>
        <textarea name="descripcion" placeholder="descripcion"></textarea><br><br>
        <input type="file" name="imagen" placeholder="imagen"><br><br>
        <button type="submit">enviar</button>
    </form>

{% endblock %}

app/templates/bienvenida.html
{% extends 'layout.html' %}

{% block content %}
<header class="hero animate-on-scroll">
    <div class="hero-content">
        <h1 class="hero-title">Hola <strong style="color: var(--color-naranja-oscuro);">{{session.nombre}}</strong><br>Bienvenido a la Biblioteca Online</h1>
        <p class="hero-description">Descubre, explora y disfruta de nuestra colección de libros. Todo al alcance de un clic.</p>
        <a href="{{ url_for('libros.libross') }}" class="hero-btn">Explorar Libros</a>
    </div>
</header>
<div class="libros-mas-valorados animate-on-scroll">
    <h2>Libros más valorados</h2>
    <div class="libros-blog-container">
        {% for libro in libros_mas_valorados %}
        <div class="libro-blog-card animate-on-scroll">
            <div class="libro-img-container">
                <img class="imagen-card" src="{{ url_for('static', filename='img/' ~ libro.img) }}" alt="{{ libro.titulo }}">
            </div>
            <div class="libro-content">
                <h3>{{ libro.titulo }}</h3>
                <p class="descripcion">{{ libro.descripcion[:200] }}...</p>
                <p class="precio">Precio: ${{ libro.precio }}</p>
                <p class="calificacion">⭐ Promedio: {{ libro.promedio_estrellas | round(1) }}</p>
                <a href="{{ url_for('libros.detalle', libro_id=libro.id) }}" class="btn-leer-mas">Ver más</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

app/templates/editarlibro.html
{% extends 'layout.html' %}

{% block content %}
<form action="/editarlibro/{{libros.id}}" method="POST">
    <label for="nombre_libro">Nombre del Libro:</label>
    <input type="text" id="nombre_libro" name="nombre_libro" value="{{ libros.nombre_s }}" ><br>
    
    <label for="autor">Autor:</label>
    <input type="text" id="autor" name="autor" value="{{ libros.autor }}" ><br>
    
    <label for="fecha_creacion">Fecha de Creación:</label>
    <input type="date" id="fecha_creacion" name="fecha_creacion" value="{{ libros.fecha_creacion }}" ><br>
    
    <label for="stock">Stock:</label>
    <input type="number" id="stock" name="stock" value="{{ libros.stock }}" ><br>
    
    <label for="precio">Precio:</label>
    <input type="number" id="precio" name="precio" value="{{ libros.precio }}" ><br>

    <label for="descripcion">descripcion:</label>
    <input type="text" id="precio" name="descripcion" value="{{ libros.descripcion }}" ><br>

    <label for="imagen">imagen:</label>
    <input type="text" id="precio" name="imagen" value="{{ libros.imagen }}" ><br>
    
    <button type="submit">Guardar Cambios</button>
</form>
    {% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/tabla.css' ) }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/navbar.css' ) }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css' ) }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/detalles.css' ) }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/paginacion.css' ) }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/cards.css' ) }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/carousel.css' ) }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/filtro.css' ) }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/footer.css' ) }}">
    <!-- iconos -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&icon_names=shopping_cart" />
    <title>Libreria Flask</title>
</head>
<body>
<!-- Navbar -->
<nav>
  <ul class="menu">
    <li class="logo"><a href="{{url_for('libros.bienvenida')}}"><strong style="color: #3e518b; font-size: 30px;">Libro</strong><strong style="color: #cf6f37; font-size: 30px;">Teca</strong></a></li>
    <li class="item"><a href="{{url_for('libros.bienvenida')}}">Inicio</a></li>
    <li class="item"><a href="{{url_for('libros.libross')}}">ver libros</a></li>
    <li class="item has-submenu">
      {% if session.get('rol') == 'admin' %}
      
      <a style="overflow: hidden;" tabindex="-1" >admin <i class="fas fa-bars">▼</i></a>
      
      <style>
        
      </style>
      <ul class="submenu" style="z-index: 3;">
        <li class="subitem"><a href="{{url_for('libros.verlibro')}}">manejar libros</a></li>
        <li class="subitem"><a href="{{url_for('prestamos.ver_todos_prestamos')}}">manejar ventas</a></li>
       
      </ul>
      {% endif %}
    </li>

    </li>
    {% if "nombre" in session %}
    <li class="item"><a href="{{url_for('prestamos.listar_prestamos')}}"><span class="material-symbols-outlined">
      shopping_cart
      </span></a></li>
    {% endif %}

    {% if "nombre" in session %}
    <li class="item button"><a href="{{url_for('user.logout')}}" onclick="return confirm('¿Estás seguro de que deseas cerrar sesion?');">cerrar sesion</a>
    {% endif %}
    </li>
    {% if "nombre" not in session %}
    <li class="item button"><a href="{{url_for('user.index_login')}}">iniciar sesion</a></li>
    <li class="item button secondary"><a href="{{url_for('user.register')}}">Registrarse</a></li>
    {% endif %}
    <li  class="toggle"><button id="boton-menu" class="fas fa-bars">
      <div></div>
      <div></div>
      <div></div>
    </button></li>
      
  </ul>
</nav>
<script src="{{ url_for('static', filename='js/script.js') }}"></script>

<main id="main">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
      <ul class=flashes style="position: sticky;">
      {% for message in messages %}
        <li>{{ message }}</li>
      {% endfor %}
      </ul>
    {% endif %}
  {% endwith %}
    {% block content %}
    {% endblock %}
    <footer class="footer">
      <div class="footer-container">
          <div class="footer-section">
              <h4>Información</h4>
              <p>Esta es una librería online realizada con la unica intencion de aprender. <br> ninguno de los libros esta a la venta.</p>
              <p>Contáctanos: Libreria@example.com</p>
          </div>
          <div class="footer-section">
              <h4>Enlaces útiles</h4>
              <ul>
                  <li><a href="{{url_for('libros.bienvenida')}}">Inicio</a></li>
                  <li><a href="{{url_for('libros.libross')}}">Libros</a></li>
                  <li><a href="https://i.pinimg.com/564x/1c/7e/a8/1c7ea8a874fedb708bdf6116cd661ebe.jpg" target="_blank">Contacto</a></li>
                  <li><a href="{{url_for('libros.condiciones')}}" target="_blank">Términos y condiciones</a></li>
              </ul>
          </div>
          <div class="footer-section">
              <h4>Redes sociales</h4>
              <div class="social-icons">
                  <a href="https://i.pinimg.com/564x/25/bb/2a/25bb2a2c9c4f99cc3a23345d411c2766.jpg" target="_blank"><img src="{{ url_for('static', filename='imagen/twitter-alt.svg') }}" alt="Facebook"></a>
                  <a href="https://i.pinimg.com/564x/f7/21/d6/f721d64137a79d524ad8b5a5de788185.jpg" target="_blank"><img src="{{ url_for('static', filename='imagen/facebook.svg') }}" alt="Twitter"></a>
                  <a href="https://www.instagram.com/piquetnacho/" target="_blank"><img src="{{ url_for('static', filename='imagen/Instagram.svg') }}" alt="Instagram"></a>
                  
              </div>
          </div>
      </div>
      <div class="footer-bottom">
          <p>&copy; 2024 Librería. Todos los derechos reservados.</p>
      </div>
  </footer>
  
  </main>
</body>
</html>

app/templates/terminos_condiciones.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Términos y Condiciones | Librería Meme</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="container">
        <h1>Términos y Condiciones 📚</h1>
        <p>Bienvenido a la sección donde, si llegaste hasta aquí, probablemente te aburres... pero no te preocupes, ¡intentaremos que sea divertido! 😎</p>
        
        <h2>1. Introducción</h2>
        <p>
            Al usar nuestra increíble <b>Librería Meme</b> (donde puedes alquilar y vender libros, ¡qué sorpresa!), aceptas estos términos, o al menos finges haberlos leído. 🙃
        </p>
        
        <h2>2. Tus derechos como lector 🧠</h2>
        <ul>
            <li>Tienes derecho a leer todo lo que quieras. Ya sea una novela, un cómic o ese libro que nunca acabas. 📖</li>
            <li>Puedes devolver el libro antes de la fecha límite... o bueno, pagar la multa si te olvidaste. 😅</li>
            <li>Tienes derecho a enamorarte de un personaje de ficción (no somos responsables si tu corazón es roto 💔).</li>
        </ul>
        
        <h2>3. Obligaciones (porque la vida es así) 😬</h2>
        <ul>
            <li>Debes tratar los libros como si fueran de oro (aunque solo cuesten $5). 📚💰</li>
            <li>Si dañas un libro, podrías tener que sacrificar tu alma (o pagar por el libro, lo que sea más fácil). 😇</li>
            <li>No uses las páginas como servilletas. Lo sabemos, a veces es tentador. 🍕</li>
        </ul>
        
        <h2>4. Políticas de devolución</h2>
        <p>
            Si devuelves un libro tarde, te perseguiremos (con emails amables) hasta que lo devuelvas. También aceptamos sobornos en forma de café. ☕
        </p>
        
        <h2>5. ¿Privacidad? ¿Qué es eso? 🔒</h2>
        <p>
            Nos importa tu privacidad, pero no podemos prometer que no usaremos tus datos para entrenar un ejército que dominará el mundo. 🌎🛸
        </p>
        
        <h2>6. Cambios en los términos</h2>
        <p>
            Nos reservamos el derecho a cambiar estos términos cuando nos plazca, porque somos así de cool. Si no te gusta, siempre puedes cerrar esta pestaña. 🚪🚶
        </p>
        
        <h2>7. ¿Algo más?</h2>
        <p>Probablemente no... pero si tienes dudas, ¡contáctanos! Aunque seguramente no responderemos. 💬😂</p>
        
        <div class="footer">
            <p>Gracias por ser tan valiente y leer hasta aquí. 🎉</p>
        </div>
    </div>
</body>
<style>
    body {
    font-family: 'Comic Sans MS', cursive, sans-serif;
    margin: 0;
    padding: 0;
    color: #333;
    background-color: darkgray;
}

.container {
    width: 80%;
    margin: 0 auto;
    padding: 20px;
    border: 2px solid #e0e0e0;
    border-radius: 10px;
    box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
}

h1 {
    color: #ff6347;
    text-align: center;
    font-size: 3em;
    margin-bottom: 20px;
}

h2 {
    color: #4b0082;
    font-size: 1.8em;
}

p {
    font-size: 1.1em;
    line-height: 1.6;
}

ul {
    list-style: none;
    padding-left: 20px;
}

ul li {
    font-size: 1.2em;
    margin-bottom: 10px;
}

ul li:before {
    content: "✔️ ";
    margin-right: 5px;
}

.footer {
    text-align: center;
    margin-top: 30px;
}

.footer p {
    font-size: 1.5em;
    color: #ff4500;
}

@media (max-width: 768px) {
    .container {
        width: 95%;
    }

    h1 {
        font-size: 2em;
    }

    h2 {
        font-size: 1.5em;
    }

    p, ul li {
        font-size: 1em;
    }
}

</style>
</html>

app/templates/verlibros.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Libros</title>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid black;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <h1>Lista de Libros</h1>
    <table>
        <thead>
            <tr>
                <th>Título</th>
                <th>Autor</th>
                <th>Descripción</th>
                <th>Fecha de Emisión</th>
                <th>Stock</th>
                <th>Precio</th>
                <th>Imagen</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for libro in libros %}
            {{libro}}
            <tr>
                <td>{{ libro.titulo }}</td>
                <td>{{ libro.autor }}</td>
                <td>{{ libro.descripcion }}</td>
                <td>{{ libro.fecha_emision }}</td>
                <td>{{ libro.stock }}</td>
                <td>${{ libro.precio }}</td>
                <td><img src="{{ libro.img }}" alt="Imagen del libro" width="100"></td>
                <td>
                    <a href="{{ url_for('libros.eliminarlibro', id=libro.id) }}">Eliminar</a>
                    <a href="{{ url_for('libros.editarlibro', id=libro.id) }}">Editar</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>